# Generated by Django 4.1.6 on 2023-02-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bd_eng_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Value_Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bd_no', models.CharField(max_length=20)),
            ],
        ),
    ]
