# Generated by Django 4.1.6 on 2023-02-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_process_chain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_domain',
            name='bd_eng_name',
        ),
        migrations.RemoveField(
            model_name='process_chain',
            name='id',
        ),
        migrations.RemoveField(
            model_name='value_chain',
            name='id',
        ),
        migrations.AddField(
            model_name='business_domain',
            name='bd_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='process_chain',
            name='bd_no',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='process_chain',
            name='pc_eng_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='process_chain',
            name='pc_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='process_chain',
            name='pc_no',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='value_chain',
            name='vc_eng_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='value_chain',
            name='vc_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='value_chain',
            name='vc_no',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process_chain',
            name='vc_no',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='value_chain',
            name='bd_no',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
