# Generated by Django 4.1.6 on 2023-02-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_business_domain_bd_eng_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_domain',
            name='id',
        ),
        migrations.AddField(
            model_name='business_domain',
            name='bd_eng_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='business_domain',
            name='bd_no',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
