# Generated by Django 4.1.6 on 2023-03-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_remove_business_domain_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component_Business',
            fields=[
                ('cb_no', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('cb_name', models.CharField(default=None, max_length=100)),
                ('cb_eng_name', models.CharField(default=None, max_length=100)),
                ('cb_type', models.CharField(default=None, max_length=50)),
                ('cb_eng_type', models.CharField(default=None, max_length=50)),
                ('pc_no', models.CharField(default=None, max_length=50)),
                ('bd_no', models.CharField(default=None, max_length=20)),
                ('vc_no', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
