# Generated by Django 4.1.6 on 2023-03-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_component_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_business',
            name='cb_no',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False),
        ),
    ]
