# Generated by Django 4.1.6 on 2023-03-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_component_business_cb_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_business',
            name='cb_no',
            field=models.BigIntegerField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
