# Generated by Django 4.1.6 on 2023-03-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_component_business_cb_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_business',
            name='cb_no',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
