# Generated by Django 4.1.6 on 2023-03-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_component_business_cb_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_business',
            name='bd_no',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='component_business',
            name='cb_eng_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='component_business',
            name='cb_eng_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='component_business',
            name='cb_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='component_business',
            name='cb_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='component_business',
            name='cb_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='component_business',
            name='pc_no',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='component_business',
            name='vc_no',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
