# Generated by Django 4.1.6 on 2023-03-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_component_business_bd_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component_Activity',
            fields=[
                ('ca_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ca_name', models.CharField(default=None, max_length=100, null=True)),
                ('ca_eng_name', models.CharField(default=None, max_length=100, null=True)),
                ('cb_no', models.BigIntegerField(default=None, null=True)),
                ('pc_no', models.CharField(default=None, max_length=50, null=True)),
                ('bd_no', models.CharField(default=None, max_length=20, null=True)),
                ('vc_no', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
