# Generated by Django 4.1.6 on 2023-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_component_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rollout_Info',
            fields=[
                ('ri_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(default=None, max_length=50, null=True)),
                ('go_live_date', models.DateField(null=True)),
                ('cb_no', models.BigIntegerField(default=None, null=True)),
                ('pc_no', models.CharField(default=None, max_length=50, null=True)),
                ('bd_no', models.CharField(default=None, max_length=20, null=True)),
                ('vc_no', models.CharField(default=None, max_length=50, null=True)),
                ('ca_no', models.BigIntegerField(default=None, null=True)),
                ('sl_no', models.BigIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System_List',
            fields=[
                ('sl_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(default=None, max_length=200, null=True)),
                ('system_eng_name', models.CharField(default=None, max_length=200, null=True)),
                ('usecase_name', models.CharField(default=None, max_length=200, null=True)),
                ('usecase_eng_name', models.CharField(default=None, max_length=200, null=True)),
                ('flywheel_no', models.CharField(default=None, max_length=200, null=True)),
                ('belong_platform', models.CharField(default=None, max_length=200, null=True)),
                ('cb_no', models.BigIntegerField(default=None, null=True)),
                ('pc_no', models.CharField(default=None, max_length=50, null=True)),
                ('bd_no', models.CharField(default=None, max_length=20, null=True)),
                ('vc_no', models.CharField(default=None, max_length=50, null=True)),
                ('ca_no', models.BigIntegerField(default=None, null=True)),
            ],
        ),
    ]
