# Generated by Django 4.1.6 on 2023-03-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_rollout_info_system_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_list',
            name='is_package',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
