# Generated by Django 4.1.6 on 2023-03-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_system_list_is_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollout_info',
            name='bd_no',
        ),
        migrations.RemoveField(
            model_name='rollout_info',
            name='ca_no',
        ),
        migrations.RemoveField(
            model_name='rollout_info',
            name='cb_no',
        ),
        migrations.RemoveField(
            model_name='rollout_info',
            name='pc_no',
        ),
        migrations.RemoveField(
            model_name='rollout_info',
            name='vc_no',
        ),
    ]
