# Generated by Django 4.1.6 on 2023-03-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_remove_rollout_info_bd_no_remove_rollout_info_ca_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollout_info',
            name='current_use_status',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
